highlighter: rouge
github: [Repository metadata]

baseurl: "http://kristenzirkler.github.io/kz-jekyll-boilerplate"
livereload: true

# Sass
sass:
  sass_dir: scss
  style: :expanded
  line_numbers: true